# Generated by Django 5.2.3 on 2025-07-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dummy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(default='assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.student')),
            ],
        ),
    ]
